baseurl      = "localhost"
title        = "Rylan's Tech Blog"
theme        = "hugo-theme-techdoc"
languageCode = "en-us"
paginate     = 10

[params]
    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/thingsym/hugo-theme-techdoc"
    github_doc_repository_path = ""
    github_doc_repository_branch = "master"
    
    menu_style = "open-menu"

